# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PackTextures.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PackTextures(object):
    def setupUi(self, PackTextures):
        PackTextures.setObjectName("PackTextures")
        PackTextures.resize(806, 481)
        self.centralwidget = QtWidgets.QWidget(PackTextures)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(320, 20, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.PackButton = QtWidgets.QPushButton(self.centralwidget)
        self.PackButton.setGeometry(QtCore.QRect(340, 400, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PackButton.setFont(font)
        self.PackButton.setObjectName("PackButton")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 90, 371, 291))
        self.listView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 101, 32))
        font = QtGui.QFont()
        font.setFamily("Montserrat Light")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(420, 88, 371, 291))
        self.listView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listView_2.setObjectName("listView_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Light")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 60, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Light")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(390, 90, 31, 291))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        PackTextures.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PackTextures)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        PackTextures.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PackTextures)
        self.statusbar.setObjectName("statusbar")
        PackTextures.setStatusBar(self.statusbar)

        self.retranslateUi(PackTextures)
        QtCore.QMetaObject.connectSlotsByName(PackTextures)

    def retranslateUi(self, PackTextures):
        _translate = QtCore.QCoreApplication.translate
        PackTextures.setWindowTitle(_translate("PackTextures", "PackTextures"))
        self.comboBox.setItemText(0, _translate("PackTextures", "Groom - ORM"))
        self.comboBox.setItemText(1, _translate("PackTextures", "Terrain - CR"))
        self.comboBox.setItemText(2, _translate("PackTextures", "Terrain - NOH"))
        self.comboBox.setItemText(3, _translate("PackTextures", "Body - ARM"))
        self.PackButton.setText(_translate("PackTextures", "PACK"))
        self.pushButton.setText(_translate("PackTextures", "Load Texture Files"))
        self.label.setText(_translate("PackTextures", "Pack Preset:"))
        self.label_2.setText(_translate("PackTextures", "Inputs Files:"))
        self.label_3.setText(_translate("PackTextures", "Output Files:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PackTextures = QtWidgets.QMainWindow()
    ui = Ui_PackTextures()
    ui.setupUi(PackTextures)
    PackTextures.show()
    sys.exit(app.exec_())
